### ISSUE TITLE
Hasn't the paper been published yet?

### ISSUE THREAD

**Issue by lan720** [dwgnr/speech-conversion#2]
Hasn't the paper been published yet

**Comment by dwgnr** [comment]
Hi, no it has not yet been published. The paper is going to be presented at SLT in January (https://slt2022.org/). 
I can upload a preprint to arxiv if you're interested.

**Comment by lan720** [comment]
> Hi, no it has not yet been published. The paper is going to be presented at SLT in January (https://slt2022.org/). I can upload a preprint to arxiv if you're interested.

Thank you so much.I plan to report this article in my course report and hope you could upload it as soon as possible!

**Comment by dwgnr** [comment]
No problem. I just uploaded the paper to arxiv. It is currently scheduled to be available at Tue, 6 Dec 2022 01:00:00 GMT. Will post the URL here as soon as it's out.

**Comment by dwgnr** [comment]
The paper is now available at https://arxiv.org/abs/2212.01775

**Comment by lan720** [comment]
> The paper is now available at https://arxiv.org/abs/2212.01775

Thanku.You are so kind.I have finished my presentation just now.Hope you produce more and more high-quality articles.

**Comment by dwgnr** [comment]
You're welcome. I hope your presentation goes well!
